import type { ClusterArticleStub, GuideSlug } from "../types";

export const CLUSTER_ARTICLES: ClusterArticleStub[] = [
  { slug: "how-long-does-a-roof-last", title: "How Long Does a Roof Last?", targetKeyword: "how long does a roof last", parentGuide: "roof", status: "stub", description: "Lifespan by material with real-world vs. warranty numbers." },
  { slug: "architectural-vs-3tab-shingles", title: "Architectural vs. 3-Tab Shingles", targetKeyword: "architectural vs 3 tab shingles", parentGuide: "roof", status: "stub", description: "Performance, cost, and why 3-tab is largely obsolete." },
  { slug: "how-to-inspect-your-roof-from-the-ground", title: "How to Inspect Your Roof From the Ground", targetKeyword: "how to inspect roof from ground", parentGuide: "roof", status: "stub", description: "Step-by-step walkthrough with what to look for at each roof plane." },
  { slug: "what-is-a-pipe-boot", title: "What Is a Pipe Boot and Why Does It Fail?", targetKeyword: "what is a pipe boot roof", parentGuide: "roof", status: "stub", description: "The most common source of roof leaks in homes over 10 years old." },
  { slug: "roof-flashing-types-and-failures", title: "Roof Flashing: Types, Failures, and What to Ask Your Roofer", targetKeyword: "roof flashing types", parentGuide: "roof", status: "stub", description: "Step flashing, counterflashing, kick-out flashing. Why it fails." },
  { slug: "how-ice-dams-form", title: "How Ice Dams Form (And Why More Flashing Won't Fix Them)", targetKeyword: "how do ice dams form", parentGuide: "roof", status: "stub", description: "The real cause is attic heat loss, not roofing failure." },
  { slug: "granule-loss-roof-shingles", title: "Granule Loss on Roof Shingles: What It Means", targetKeyword: "granule loss roof shingles", parentGuide: "roof", status: "stub", description: "How to measure it, what it indicates, and when it means replacement." },
  { slug: "hail-damage-roof-inspection", title: "How to Inspect Your Roof After a Hail Storm", targetKeyword: "hail damage roof inspection", parentGuide: "roof", status: "stub", description: "What hail damage looks like, what to document, and the insurance timeline." },
  { slug: "roof-replacement-cost", title: "What Does a Roof Replacement Cost in 2025?", targetKeyword: "roof replacement cost 2025", parentGuide: "roof", status: "stub", description: "National averages by material and size. How to evaluate quotes." },
  { slug: "metal-roof-pros-cons", title: "Metal Roofing: Is It Worth the Cost?", targetKeyword: "metal roof pros cons", parentGuide: "roof", status: "stub", description: "Standing seam vs. exposed fastener. Real lifespan data." },
  { slug: "how-to-find-a-good-roofer", title: "How to Find a Roofer Who Won't Cut Corners", targetKeyword: "how to find a good roofer", parentGuide: "roof", status: "stub", description: "Licensing verification, insurance checks, local references, red flags." },
  { slug: "roof-warranty-explained", title: "Roofing Warranties Explained: What's Actually Covered", targetKeyword: "roof warranty explained", parentGuide: "roof", status: "stub", description: "Manufacturer vs. workmanship warranties. Why 30-year isn't what it sounds like." },
  { slug: "class-4-impact-resistant-shingles", title: "Class 4 Impact-Resistant Shingles: Are They Worth It?", targetKeyword: "class 4 impact resistant shingles", parentGuide: "roof", status: "stub", description: "Insurance discounts, real-world performance, cost premium analysis." },
  { slug: "attic-ventilation-roof-lifespan", title: "How Attic Ventilation Affects Your Roof's Lifespan", targetKeyword: "attic ventilation roof lifespan", parentGuide: "roof", status: "stub", description: "Why overheated attics degrade shingles from below." },
  { slug: "roof-repair-vs-replacement", title: "Roof Repair vs. Replacement: How to Decide", targetKeyword: "roof repair vs replacement", parentGuide: "roof", status: "stub", description: "A decision framework based on age, damage extent, and remaining life." },
  { slug: "storm-chaser-roofing-scams", title: "Storm Chaser Roofing Scams: How to Protect Yourself", targetKeyword: "storm chaser roofing scam", parentGuide: "roof", status: "stub", description: "Red flags, why they appear after hail events, and what to do." },
  { slug: "fiber-cement-siding-maintenance", title: "Fiber Cement Siding Maintenance: The Complete Guide", targetKeyword: "fiber cement siding maintenance", parentGuide: "siding", status: "stub", description: "Paint intervals, caulking, clearance maintenance." },
  { slug: "vinyl-siding-buckling-causes", title: "Why Is My Vinyl Siding Buckling?", targetKeyword: "vinyl siding buckling", parentGuide: "siding", status: "stub", description: "Installation gap errors, heat from reflected surfaces, and fixes." },
  { slug: "how-long-does-vinyl-siding-last", title: "How Long Does Vinyl Siding Last?", targetKeyword: "how long does vinyl siding last", parentGuide: "siding", status: "stub", description: "Real-world lifespan, factors that accelerate degradation." },
  { slug: "kick-out-flashing-what-is-it", title: "Kick-Out Flashing: The $20 Part That Prevents $20,000 in Damage", targetKeyword: "kick out flashing siding", parentGuide: "siding", status: "stub", description: "What it is, where it goes, and why it's missing on so many homes." },
  { slug: "eifs-stucco-moisture-problems", title: "EIFS Moisture Problems Explained", targetKeyword: "EIFS moisture problems", parentGuide: "siding", status: "stub", description: "Why EIFS became notorious, how to spot problems." },
  { slug: "siding-caulking-guide", title: "Where to Caulk Your Siding (And What to Use)", targetKeyword: "siding caulking guide", parentGuide: "siding", status: "stub", description: "Every caulk joint that matters, product selection, application." },
  { slug: "james-hardie-siding-review", title: "James Hardie Siding: Honest Review", targetKeyword: "james hardie siding review", parentGuide: "siding", status: "stub", description: "Real performance data, paint maintenance reality." },
  { slug: "siding-replacement-cost", title: "How Much Does New Siding Cost in 2025?", targetKeyword: "siding replacement cost 2025", parentGuide: "siding", status: "stub", description: "Per-square-foot costs by material, what drives variation." },
  { slug: "how-often-clean-gutters", title: "How Often Should You Clean Your Gutters?", targetKeyword: "how often clean gutters", parentGuide: "gutters", status: "stub", description: "By climate, tree coverage, and gutter type." },
  { slug: "gutter-guard-comparison", title: "Gutter Guards Compared: Which Type Actually Works?", targetKeyword: "gutter guard comparison", parentGuide: "gutters", status: "stub", description: "Micro-mesh, reverse curve, foam, screen. Real performance data." },
  { slug: "fascia-board-rot-repair", title: "Fascia Board Rot: How to Find It and What to Do", targetKeyword: "fascia board rot repair", parentGuide: "gutters", status: "stub", description: "How to identify rot, when to repair vs. replace." },
  { slug: "downspout-drainage-solutions", title: "Downspout Drainage Solutions", targetKeyword: "downspout drainage solutions", parentGuide: "gutters", status: "stub", description: "Extensions, underground drains, french drains, and grading." },
  { slug: "seamless-vs-sectional-gutters", title: "Seamless vs. Sectional Gutters", targetKeyword: "seamless vs sectional gutters", parentGuide: "gutters", status: "stub", description: "Why seams fail, cost comparison, and why seamless wins." },
  { slug: "gutter-replacement-cost", title: "Gutter Replacement Cost in 2025", targetKeyword: "gutter replacement cost 2025", parentGuide: "gutters", status: "stub", description: "Per-linear-foot costs, what drives variation." },
  { slug: "foggy-window-repair-or-replace", title: "Foggy Windows: Repair the Glass or Replace the Window?", targetKeyword: "foggy window repair or replace", parentGuide: "windows", status: "stub", description: "IGU replacement vs. full window replacement — cost comparison." },
  { slug: "window-u-factor-explained", title: "Window U-Factor Explained in Plain English", targetKeyword: "window u factor explained", parentGuide: "windows", status: "stub", description: "What it measures, what numbers to look for by climate." },
  { slug: "double-pane-vs-triple-pane-windows", title: "Double Pane vs. Triple Pane Windows", targetKeyword: "double pane vs triple pane windows", parentGuide: "windows", status: "stub", description: "Cost premium, energy savings, payback period." },
  { slug: "vinyl-vs-fiberglass-windows", title: "Vinyl vs. Fiberglass Windows", targetKeyword: "vinyl vs fiberglass windows", parentGuide: "windows", status: "stub", description: "Performance comparison, cost difference, upgrade value." },
  { slug: "window-condensation-causes", title: "Window Condensation: What Each Type Means", targetKeyword: "window condensation causes", parentGuide: "windows", status: "stub", description: "Interior, exterior, and between panes — three different problems." },
  { slug: "low-e-glass-explained", title: "Low-E Glass Explained", targetKeyword: "low e glass explained", parentGuide: "windows", status: "stub", description: "Soft vs. hard coat, solar control, how to match to your climate." },
  { slug: "window-replacement-cost", title: "Window Replacement Cost in 2025", targetKeyword: "window replacement cost 2025", parentGuide: "windows", status: "stub", description: "National averages, full-frame vs. insert, how to evaluate quotes." },
  { slug: "hvac-filter-replacement-guide", title: "HVAC Filter Replacement: How Often, What Size, What Rating", targetKeyword: "hvac filter replacement guide", parentGuide: "hvac", status: "stub", description: "MERV ratings, 1-inch vs. 4-inch filters, actual replacement frequency." },
  { slug: "ac-not-cooling-causes", title: "AC Running But Not Cooling: Most Common Causes", targetKeyword: "ac running but not cooling", parentGuide: "hvac", status: "stub", description: "Refrigerant, capacitor, coils, airflow — how to diagnose." },
  { slug: "hvac-tune-up-what-it-includes", title: "What Should an HVAC Tune-Up Actually Include?", targetKeyword: "what does hvac tune up include", parentGuide: "hvac", status: "stub", description: "A real checklist so you know what you paid for." },
  { slug: "heat-pump-vs-gas-furnace", title: "Heat Pump vs. Gas Furnace", targetKeyword: "heat pump vs gas furnace", parentGuide: "hvac", status: "stub", description: "Climate-specific analysis, operating cost comparison." },
  { slug: "when-to-replace-hvac", title: "When Should You Replace Your HVAC System?", targetKeyword: "when to replace hvac system", parentGuide: "hvac", status: "stub", description: "The 5,000 rule, age thresholds, efficiency comparison." },
  { slug: "hvac-refrigerant-leak-signs", title: "Signs Your HVAC Has a Refrigerant Leak", targetKeyword: "hvac refrigerant leak signs", parentGuide: "hvac", status: "stub", description: "How to tell, why recharging without fixing the leak is wrong." },
  { slug: "what-is-hvac-seer-rating", title: "HVAC SEER Ratings Explained", targetKeyword: "hvac seer rating explained", parentGuide: "hvac", status: "stub", description: "What SEER measures, the minimum vs. the smart choice." },
  { slug: "hvac-cracked-heat-exchanger", title: "Cracked Heat Exchanger: Real Risk or Contractor Upsell?", targetKeyword: "cracked heat exchanger hvac", parentGuide: "hvac", status: "stub", description: "What it means, how to verify the claim, when to replace." },
  { slug: "ductless-mini-split-pros-cons", title: "Ductless Mini-Splits: Are They Worth It?", targetKeyword: "ductless mini split pros cons", parentGuide: "hvac", status: "stub", description: "Efficiency, cost, zone control, ideal use cases." },
  { slug: "hvac-replacement-cost", title: "HVAC Replacement Cost in 2025", targetKeyword: "hvac replacement cost 2025", parentGuide: "hvac", status: "stub", description: "By system type and size. What drives variation." },
  { slug: "water-heater-anode-rod-replacement", title: "Water Heater Anode Rod: What It Is and When to Replace It", targetKeyword: "water heater anode rod replacement", parentGuide: "water-heater", status: "stub", description: "The most underutilized maintenance item in residential plumbing." },
  { slug: "how-to-flush-water-heater", title: "How to Flush Your Water Heater", targetKeyword: "how to flush water heater", parentGuide: "water-heater", status: "stub", description: "Why it matters, how often, and the full process with safety steps." },
  { slug: "tankless-water-heater-pros-cons", title: "Tankless Water Heaters: Honest Pros and Cons", targetKeyword: "tankless water heater pros cons", parentGuide: "water-heater", status: "stub", description: "Efficiency numbers, cost premium, installation requirements." },
  { slug: "water-heater-tpr-valve-test", title: "How to Test Your Water Heater TPR Valve", targetKeyword: "water heater tpr valve test", parentGuide: "water-heater", status: "stub", description: "Why it matters, the 10-second test, what to do if it fails." },
  { slug: "heat-pump-water-heater-review", title: "Heat Pump Water Heaters: Are They Worth It in 2025?", targetKeyword: "heat pump water heater review 2025", parentGuide: "water-heater", status: "stub", description: "Efficiency data, federal tax credits, installation requirements." },
  { slug: "water-heater-lifespan", title: "How Long Do Water Heaters Last?", targetKeyword: "how long does a water heater last", parentGuide: "water-heater", status: "stub", description: "By type, with real-world vs. rated lifespan." },
  { slug: "water-heater-expansion-tank", title: "Do You Need a Water Heater Expansion Tank?", targetKeyword: "water heater expansion tank", parentGuide: "water-heater", status: "stub", description: "Closed vs. open systems, code requirements, how to test if failed." },
  { slug: "water-heater-replacement-cost", title: "Water Heater Replacement Cost in 2025", targetKeyword: "water heater replacement cost 2025", parentGuide: "water-heater", status: "stub", description: "By type and size. Tankless vs. tank cost comparison." },
  { slug: "weatherstripping-replacement-guide", title: "How to Replace Door Weatherstripping", targetKeyword: "weatherstripping replacement guide", parentGuide: "entry-doors", status: "stub", description: "Types, how to measure, and the installation process." },
  { slug: "fiberglass-vs-steel-door", title: "Fiberglass vs. Steel Entry Door", targetKeyword: "fiberglass vs steel entry door", parentGuide: "entry-doors", status: "stub", description: "Performance comparison, cost difference, when the upgrade pays off." },
  { slug: "entry-door-security-upgrade", title: "The Most Effective Entry Door Security Upgrades", targetKeyword: "entry door security upgrade", parentGuide: "entry-doors", status: "stub", description: "Strike plate upgrade, Grade 1 deadbolt, door reinforcement kits." },
  { slug: "entry-door-replacement-cost", title: "Entry Door Replacement Cost in 2025", targetKeyword: "entry door replacement cost 2025", parentGuide: "entry-doors", status: "stub", description: "By material, with installation. What impacts the quote." },
  { slug: "sliding-door-hard-to-open", title: "Sliding Door Hard to Open: How to Fix It Yourself", targetKeyword: "sliding door hard to open fix", parentGuide: "sliding-doors", status: "stub", description: "Track cleaning, roller adjustment, roller replacement — in order." },
  { slug: "sliding-door-security-tips", title: "Sliding Glass Door Security: What Actually Works", targetKeyword: "sliding door security tips", parentGuide: "sliding-doors", status: "stub", description: "Anti-lift pins, security bars, lock upgrades." },
  { slug: "sliding-door-roller-replacement", title: "How to Replace Sliding Door Rollers", targetKeyword: "sliding door roller replacement", parentGuide: "sliding-doors", status: "stub", description: "How to identify failed rollers and the replacement process." },
  { slug: "sliding-door-track-cleaning", title: "How to Clean and Lubricate a Sliding Door Track", targetKeyword: "sliding door track cleaning", parentGuide: "sliding-doors", status: "stub", description: "What to use, what not to use, how often." },
  { slug: "sliding-door-replacement-cost", title: "Sliding Glass Door Replacement Cost in 2025", targetKeyword: "sliding door replacement cost 2025", parentGuide: "sliding-doors", status: "stub", description: "By size and material. Energy performance considerations." },
];

export function getClustersByGuide(slug: GuideSlug): ClusterArticleStub[] {
  return CLUSTER_ARTICLES.filter((a) => a.parentGuide === slug);
}

export function getPublishedClusters(): ClusterArticleStub[] {
  return CLUSTER_ARTICLES.filter((a) => a.status === "published");
}

export const CLUSTER_SUMMARY = {
  total: CLUSTER_ARTICLES.length,
  byGuide: {
    roof: CLUSTER_ARTICLES.filter((a) => a.parentGuide === "roof").length,
    siding: CLUSTER_ARTICLES.filter((a) => a.parentGuide === "siding").length,
    gutters: CLUSTER_ARTICLES.filter((a) => a.parentGuide === "gutters").length,
    windows: CLUSTER_ARTICLES.filter((a) => a.parentGuide === "windows").length,
    hvac: CLUSTER_ARTICLES.filter((a) => a.parentGuide === "hvac").length,
    "water-heater": CLUSTER_ARTICLES.filter((a) => a.parentGuide === "water-heater").length,
    "entry-doors": CLUSTER_ARTICLES.filter((a) => a.parentGuide === "entry-doors").length,
    "sliding-doors": CLUSTER_ARTICLES.filter((a) => a.parentGuide === "sliding-doors").length,
  },
};
